<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied!' => '¡Acceso denegado!',
    'Announcement not found!' => '¡Anuncio no encontrado!',
    'Could not load Announcement!' => '¡No se pudo cargar el anuncio!',
    'Users didn\'t read this <strong>{title}</strong>' => 'Los usuarios no leyeron esto <strong>{title}</strong>',
    'Users who read this <strong>{title}</strong>' => 'Usuarios que leen esto <strong>{title}</strong>',
    'You have insufficient permissions to perform that operation!' => '¡No tiene permisos suficientes para realizar esa operación!',
];
